name: Build MAUI Apps

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry


jobs:
# ***************************** #
# >>>>>>> Android build <<<<<<< #
# ***************************** #
  build-android:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'

    - name: Setup Java
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'microsoft'
        java-version: '11'
        
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
      
    - name: Restore Dependencies
      run: dotnet restore MauiApp1/MauiApp1.csproj

    - name: Build MAUI Android
      run: dotnet publish MauiApp1/MauiApp1.csproj -f net8.0-android -c Release --no-restore

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: MauiApp1-android-ci-build
        path: MauiApp1/bin/Release/net8.0-android/*mauiapp1.a*

    
# ***************************** #
# >>>>>>> Windows Build <<<<<<< #
# ***************************** #
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
    
    - name: Restore Dependencies
      run: dotnet restore MauiApp1/MauiApp1.csproj

    - name: Decrypt PFX File
      run: |
        echo "${{ secrets.WINDOWS_PFX_FILE }}" > cert.pfx.asc
        certutil -decode cert.pfx.asc cert.pfx
    
    - name: Add Cert to Store
      run: certutil -user -q -p ${{ secrets.WINDOWS_PFX_PASSWORD }} -importpfx cert.pfx NoRoot
    
    - name: Build MAUI Windows
      run: dotnet publish MauiApp1/MauiApp1.csproj -c Release -f:net8.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.WINDOWS_PFX_THUMBPRINT }}"
    
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: MauiApp1-windows-ci-build
        path: .\**\AppPackages\**\*.*

# ************************* #
# >>>>>>> iOS Build <<<<<<< #
# ************************* #
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'
        
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
    
    - name: Restore Dependencies
      run: dotnet restore MauiApp1/MauiApp1.csproj
      
    - name: Build MAUI iOS project
      shell: bash
      run: dotnet publish MauiApp1/MauiApp1.csproj -c Release -f:net8.0-ios  --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False
    
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: MauiApp1-ios-ci-build
        path: MauiApp1/bin/Release/net8.0-ios/iossimulator-x64/**/*.app

# ********************************* #
# >>>>>>> MacCatalyst Build <<<<<<< #
# ********************************* #
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
    
    - name: Restore Dependencies
      run: dotnet restore MauiApp1/MauiApp1.csproj
      
    - name: Build MAUI MacCatalyst .app
      run: dotnet publish MauiApp1/MauiApp1.csproj -c Release -f:net8.0-maccatalyst -p:CreatePackage=false
    
    - name: Upload MacCatalyst Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: macos-ci-build .app
        path: MauiApp1/bin/Release/net8.0-maccatalyst/**/*.app/
    
