name: Build MAUI Apps

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ master ]


jobs:
# ***************************** #
# >>>>>>> Android build <<<<<<< #
# ***************************** #
  build-android:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
    - uses: actions/checkout@v4.1.1

    - name: Setup .NET
    - uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'

    - name: Setup Java
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: 'microsoft'
        java-version: '11'
        
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

    - name: Build MAUI Android
      run: dotnet publish MauiApp1Test/MauiApp1.csproj -c Release -f net8.0-android --no-restore

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: MauiApp1-android-ci-build
        path: MauiApp1/bin/Release/net8.0-android/*mauiapp1.a*

    
