name: Test MAUI Apps

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry


jobs:
  test-report:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'
    
    - name: Build App
      run: dotnet build MauiApp1/MauiApp1.csproj -c Release -f:net8.0-windows10.0.19041.0 --no-restore
      
    - name: Test
      run: dotnet test Tests --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" || true 

    - name: Publish Test Result
      uses: EnricoMi/publish-unit-test-result-action@v2.14.0
      if: always()
      with:
        name: DotNET Tests
        trx_files: "**/test-results.trx"


  test-report-error:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'
    
    - name: Build App
      run: dotnet build MauiApp1/MauiApp1.csproj -c Release -f:net8.0-windows10.0.19041.0 --no-restore
      
    - name: Test
      run: dotnet test TestError --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" || true 

    - name: Publish Test Result Error
      uses: EnricoMi/publish-unit-test-result-action@v2.14.0
      if: always()
      with:
        name: DotNET Tests Error
        trx_files: "**/test-error-results.trx"
